### ISSUE TITLE
Hw 8 calculates the wrong answer

### ISSUE THREAD

**Issue by pigpenguin** [bschwb/cis194-solutions#1]
The algorithm in assignment 8 calculates the wrong maximum fun on the test companies. 

When given testCompany from the Employee.hs file it correctly calculates that the most fun they can have is 26 however it says this is done by inviting Stan and Sarah worth 9 and 17 fun respectively. Except Stan is Sarah's boss in the testCompany tree so Sarah should be worth 0 fun.

**Comment by bschwb** [comment]
Thank you very much!

The nextLevel function was wrong. Previously I added the boss to all GuestLists.
Though the correct way is to add the boss only to the lists which do not contain the employees just beneath him.
